[general]
live_config_reload = false
import = [
    "~/.config/alacritty/theme.toml",
]

[window]
opacity = 0.9
blur = true

[window.dimensions]
columns=80
lines=24

[window.padding]
x = 7
y = 0

[font]
size = 10

[cursor.style]
blinking = "On"
